name: Update Pegel

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests pandas

      - run: python pegel.py

      - name: Commit CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatisches Pegel-Update"
